/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
 *
 * Controller for the "event" collection.
 * Maps HTTP requests onto the generated service only.
 *
 * Generated by lib/collection-module-generator.ts.
 */
import type { NextApiRequest, NextApiResponse } from 'next';
import { ApiResponse } from '@/lib/types';
import * as EventService from '@/services/event.service';

function sendError(
  res: NextApiResponse<ApiResponse>,
  error: any,
  context: string
): void {
  console.error('[Event Controller]', context, error);
  const statusCode =
    typeof error?.statusCode === 'number' ? error.statusCode : 500;
  res.status(statusCode).json({
    error: error?.message || 'Internal server error',
  });
}

function readEntryId(req: NextApiRequest): string | null {
  const { id } = req.query;
  return typeof id === 'string' ? id : null;
}

/**
 * GET /api/collections/event
 */
export async function listEntries(
  req: NextApiRequest,
  res: NextApiResponse<ApiResponse>
): Promise<void> {
  try {
    const entries = await EventService.listEntries({
      populate: req.query.populate === 'true',
    });
    res.status(200).json({ data: entries });
  } catch (error: any) {
    sendError(res, error, 'Failed to list entries');
  }
}

/**
 * POST /api/collections/event
 */
export async function createEntry(
  req: NextApiRequest,
  res: NextApiResponse<ApiResponse>
): Promise<void> {
  try {
    const entryData = (req.body && req.body.data) || {};
    const entry = await EventService.createEntry(entryData);
    res.status(201).json({ data: entry });
  } catch (error: any) {
    sendError(res, error, 'Failed to create entry');
  }
}

/**
 * GET /api/collections/event/[id]
 */
export async function getEntry(
  req: NextApiRequest,
  res: NextApiResponse<ApiResponse>
): Promise<void> {
  try {
    const id = readEntryId(req);
    if (!id) {
      res.status(400).json({ error: 'Invalid entry id' });
      return;
    }
    const entry = await EventService.getEntry(id, {
      populate: req.query.populate === 'true',
    });
    res.status(200).json({ data: entry });
  } catch (error: any) {
    sendError(res, error, 'Failed to get entry');
  }
}

/**
 * PUT /api/collections/event/[id]
 */
export async function updateEntry(
  req: NextApiRequest,
  res: NextApiResponse<ApiResponse>
): Promise<void> {
  try {
    const id = readEntryId(req);
    if (!id) {
      res.status(400).json({ error: 'Invalid entry id' });
      return;
    }
    const entryData = (req.body && req.body.data) || {};
    const entry = await EventService.updateEntry(id, entryData);
    res.status(200).json({ data: entry });
  } catch (error: any) {
    sendError(res, error, 'Failed to update entry');
  }
}

/**
 * DELETE /api/collections/event/[id]
 */
export async function deleteEntry(
  req: NextApiRequest,
  res: NextApiResponse<ApiResponse>
): Promise<void> {
  try {
    const id = readEntryId(req);
    if (!id) {
      res.status(400).json({ error: 'Invalid entry id' });
      return;
    }
    await EventService.deleteEntry(id);
    res.status(200).json({ message: 'Entry deleted' });
  } catch (error: any) {
    sendError(res, error, 'Failed to delete entry');
  }
}
