-- CreateTable
CREATE TABLE "theme_settings" (
    "id" TEXT NOT NULL,
    "primaryColor" TEXT NOT NULL DEFAULT '#2563eb',
    "secondaryColor" TEXT NOT NULL DEFAULT '#0f172a',
    "accentColor" TEXT NOT NULL DEFAULT '#14b8a6',
    "successColor" TEXT NOT NULL DEFAULT '#10b981',
    "warningColor" TEXT NOT NULL DEFAULT '#f59e0b',
    "errorColor" TEXT NOT NULL DEFAULT '#ef4444',
    "backgroundColor" TEXT NOT NULL DEFAULT '#f3f4f6',
    "cardBackgroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "sidebarBackgroundColor" TEXT NOT NULL DEFAULT '#111827',
    "headerBackgroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "textColor" TEXT NOT NULL DEFAULT '#111827',
    "borderColor" TEXT NOT NULL DEFAULT '#e5e7eb',
    "primaryLogo" TEXT,
    "darkLogo" TEXT,
    "favicon" TEXT,
    "loginLogo" TEXT,
    "loginBackground" TEXT,
    "loginTitle" TEXT,
    "loginSubtitle" TEXT,
    "fontFamily" TEXT NOT NULL DEFAULT 'Inter',
    "fontScale" TEXT NOT NULL DEFAULT '1rem',
    "headingWeight" TEXT NOT NULL DEFAULT '700',
    "bodyWeight" TEXT NOT NULL DEFAULT '400',
    "sidebarWidth" TEXT NOT NULL DEFAULT '16rem',
    "borderRadius" TEXT NOT NULL DEFAULT '0.5rem',
    "buttonRadius" TEXT NOT NULL DEFAULT '0.375rem',
    "cardRadius" TEXT NOT NULL DEFAULT '0.5rem',
    "compactMode" BOOLEAN NOT NULL DEFAULT false,
    "customCss" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "theme_settings_pkey" PRIMARY KEY ("id")
);
