/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
 *
 * Service for the "blogs_cate" collection.
 * All entry data access goes through the generated model only.
 *
 * Generated by lib/collection-module-generator.ts.
 */
import * as BlogsCateModel from '@/models/blogs_cate.model';
import type { Field } from '@/lib/types';
import { resolveMultipleRelations } from '@/lib/relation-resolver';
import { populateRelations } from '@/lib/relation-populate';
import {
  populateComponents,
  populateMultipleEntries,
  createComponentEntry,
} from '@/lib/component-populate';
import { filterVirtualRelationFields } from '@/lib/relation-engine';
import {
  extractManyToManyData,
  updateManyToManyRelations,
} from '@/lib/many-to-many-handler';

function httpError(statusCode: number, message: string): Error {
  const error = new Error(message) as Error & { statusCode: number };
  error.statusCode = statusCode;
  return error;
}

/**
 * Current field definitions of the collection (fetched from metadata).
 */
async function getFields(): Promise<Field[]> {
  const collectionType = await BlogsCateModel.getCollectionType();
  if (!collectionType) {
    throw httpError(404, 'Collection type not found');
  }
  const fields = (collectionType.fields as any) || null;
  return fields && Array.isArray(fields.fields)
    ? (fields.fields as Field[])
    : [];
}

/**
 * Unique field validation (same rules as the generic collections API).
 */
async function assertUnique(
  fields: Field[],
  data: Record<string, any>,
  excludeId?: string
): Promise<void> {
  for (const field of fields) {
    if (!field.unique) continue;
    const value = data[field.name];
    if (value === undefined || value === null || value === '') continue;

    const existing = await BlogsCateModel.findMany({
      where: { [field.name]: value },
    });
    const duplicate = existing.find((row: any) => row.id !== excludeId);
    if (duplicate) {
      throw httpError(
        400,
        'This ' +
          field.displayName +
          ' already exists. The field "' +
          field.displayName +
          '" must be unique.'
      );
    }
  }
}

/**
 * Create component entries for inline component data.
 */
async function processComponentFields(
  data: Record<string, any>,
  fields: Field[]
): Promise<Record<string, any>> {
  const processed: Record<string, any> = { ...data };

  for (const field of fields) {
    if (field.type !== 'component') continue;

    const value = data[field.name];
    if (!value) continue;

    try {
      if (field.multiple) {
        if (Array.isArray(value)) {
          processed[field.name] = await Promise.all(
            value.map((item: any) => processComponentValue(item, field.componentRef!))
          );
        }
      } else {
        processed[field.name] = await processComponentValue(
          value,
          field.componentRef!
        );
      }
    } catch (error: any) {
      console.error(
        '[BlogsCate Service] Error processing field ' + field.name + ':',
        error
      );
    }
  }

  return processed;
}

async function processComponentValue(
  value: any,
  componentName: string
): Promise<string> {
  if (typeof value === 'string') return value;
  if (typeof value === 'object' && value !== null && value.id) return value.id;

  if (typeof value === 'object' && value !== null) {
    const entry = await createComponentEntry(componentName, value);
    return entry.id;
  }

  throw httpError(400, 'Invalid component value: ' + JSON.stringify(value));
}

/**
 * List entries (relations are always resolved).
 */
export async function listEntries(
  options: { populate?: boolean } = {}
): Promise<Record<string, any>[]> {
  const fields = await getFields();
  const entries = await BlogsCateModel.findMany();
  const resolved = await resolveMultipleRelations(
    entries,
    BlogsCateModel.COLLECTION_NAME,
    fields
  );

  if (options.populate) {
    return populateMultipleEntries(resolved, fields);
  }
  return resolved;
}

/**
 * Single entry with populated relations.
 */
export async function getEntry(
  id: string,
  options: { populate?: boolean } = {}
): Promise<Record<string, any>> {
  const fields = await getFields();
  const entry = await BlogsCateModel.findById(id);
  if (!entry) {
    throw httpError(404, 'Entry not found');
  }

  const resolved = await populateRelations(
    { ...entry },
    BlogsCateModel.COLLECTION_NAME,
    fields
  );

  if (options.populate) {
    return populateComponents(resolved, fields);
  }
  return resolved;
}

/**
 * Create a new entry.
 */
export async function createEntry(
  entryData: Record<string, any>
): Promise<Record<string, any>> {
  if (!entryData || Object.keys(entryData).length === 0) {
    throw httpError(400, 'Missing entry data');
  }

  const fields = await getFields();
  await assertUnique(fields, entryData);

  const processed = await processComponentFields(entryData, fields);
  const filtered = filterVirtualRelationFields(fields, processed);

  return BlogsCateModel.create(filtered);
}

/**
 * Update an existing entry.
 */
export async function updateEntry(
  id: string,
  entryData: Record<string, any>
): Promise<Record<string, any>> {
  if (!entryData || Object.keys(entryData).length === 0) {
    throw httpError(400, 'Missing entry data');
  }

  const fields = await getFields();
  await assertUnique(fields, entryData, id);

  const processed = await processComponentFields(entryData, fields);
  const { manyToManyData, cleanedData } = extractManyToManyData(
    processed,
    fields
  );
  const filtered = filterVirtualRelationFields(fields, cleanedData);

  const dataToUpdate: Record<string, any> = {};
  Object.keys(filtered).forEach((key) => {
    if (filtered[key] !== undefined) {
      dataToUpdate[key] = filtered[key];
    }
  });

  const entry = await BlogsCateModel.update(id, dataToUpdate);

  if (Object.keys(manyToManyData).length > 0) {
    await updateManyToManyRelations(
      BlogsCateModel.COLLECTION_NAME,
      id,
      manyToManyData,
      fields
    );
  }

  return entry;
}

/**
 * Delete an existing entry.
 */
export async function deleteEntry(id: string): Promise<void> {
  await getFields();
  const entry = await BlogsCateModel.findById(id);
  if (!entry) {
    throw httpError(404, 'Entry not found');
  }

  await BlogsCateModel.remove(id);
}
