-- CreateTable
CREATE TABLE "widget_settings" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL DEFAULT 'AI Chat Assistant',
    "welcomeText" TEXT NOT NULL DEFAULT 'Hi! How can I help you today?',
    "primaryColor" TEXT NOT NULL DEFAULT '#2563eb',
    "secondaryColor" TEXT NOT NULL DEFAULT '#1e293b',
    "textColor" TEXT NOT NULL DEFAULT '#ffffff',
    "bgColor" TEXT NOT NULL DEFAULT '#ffffff',
    "position" TEXT NOT NULL DEFAULT 'right',
    "marginX" INTEGER NOT NULL DEFAULT 20,
    "marginY" INTEGER NOT NULL DEFAULT 20,
    "width" INTEGER NOT NULL DEFAULT 380,
    "height" INTEGER NOT NULL DEFAULT 600,
    "borderRadius" INTEGER NOT NULL DEFAULT 16,
    "showLogo" BOOLEAN NOT NULL DEFAULT true,
    "logoUrl" TEXT,
    "logoWidth" INTEGER NOT NULL DEFAULT 40,
    "showAvatar" BOOLEAN NOT NULL DEFAULT true,
    "avatarUrl" TEXT,
    "avatarStyle" TEXT NOT NULL DEFAULT 'rounded',
    "bubbleStyle" TEXT NOT NULL DEFAULT 'rounded',
    "fontSize" TEXT NOT NULL DEFAULT '14px',
    "headerBgColor" TEXT NOT NULL DEFAULT '#2563eb',
    "headerTextColor" TEXT NOT NULL DEFAULT '#ffffff',
    "userMsgBgColor" TEXT NOT NULL DEFAULT '#2563eb',
    "userMsgTextColor" TEXT NOT NULL DEFAULT '#ffffff',
    "botMsgBgColor" TEXT NOT NULL DEFAULT '#f3f4f6',
    "botMsgTextColor" TEXT NOT NULL DEFAULT '#111827',
    "inputBgColor" TEXT NOT NULL DEFAULT '#ffffff',
    "inputBorderColor" TEXT NOT NULL DEFAULT '#e5e7eb',
    "sendButtonColor" TEXT NOT NULL DEFAULT '#2563eb',
    "sendIconColor" TEXT NOT NULL DEFAULT '#ffffff',
    "customCss" TEXT,
    "embedActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "widget_settings_pkey" PRIMARY KEY ("id")
);
