/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
 *
 * API route: /api/collections/blogs_cate/[id]
 * Delegates to the generated controller (fallback: /api/collections/[name]/[id]).
 *
 * Generated by lib/collection-module-generator.ts.
 */
import type { NextApiRequest, NextApiResponse } from 'next';
import { ApiResponse } from '@/lib/types';
import { authMiddleware } from '@/lib/middlewares/api/auth-middleware';
import * as BlogsCateController from '@/controllers/blogs_cate.controller';

async function handler(
  req: NextApiRequest,
  res: NextApiResponse<ApiResponse>
): Promise<void> {
  if (req.method === 'GET') {
    return BlogsCateController.getEntry(req, res);
  }
  if (req.method === 'PUT') {
    return BlogsCateController.updateEntry(req, res);
  }
  if (req.method === 'DELETE') {
    return BlogsCateController.deleteEntry(req, res);
  }
  res.status(405).json({ error: 'Method not allowed' });
}

export default authMiddleware(handler);
