/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
 *
 * API route: /api/collections/event_cat
 * Delegates to the generated controller (fallback: /api/collections/[name]).
 *
 * Generated by lib/collection-module-generator.ts.
 */
import type { NextApiRequest, NextApiResponse } from 'next';
import { ApiResponse } from '@/lib/types';
import { authMiddleware } from '@/lib/middlewares/api/auth-middleware';
import * as EventCatController from '@/controllers/event_cat.controller';

async function handler(
  req: NextApiRequest,
  res: NextApiResponse<ApiResponse>
): Promise<void> {
  if (req.method === 'GET') {
    return EventCatController.listEntries(req, res);
  }
  if (req.method === 'POST') {
    return EventCatController.createEntry(req, res);
  }
  res.status(405).json({ error: 'Method not allowed' });
}

export default authMiddleware(handler);
