/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
 *
 * Model for the "blog" collection.
 * Physical table: "blog"
 *
 * Generated by lib/collection-module-generator.ts.
 * Editing the collection in the Content Type Builder regenerates this file.
 */
import {
  findManyDynamic,
  findUniqueDynamic,
  createDynamic,
  updateDynamic,
  deleteDynamic,
} from '@/lib/dynamic-prisma';
import { prisma } from '@/lib/prisma';
import type { Field } from '@/lib/types';

/** Collection name as stored in the CollectionType metadata. */
export const COLLECTION_NAME = 'blog';

/** Physical PostgreSQL table backing this collection. */
export const TABLE_NAME = 'blog';

export interface BlogEntry {
  id: string;
  createdAt: string | Date;
  updatedAt: string | Date;
  name?: string;
  order?: number;
  slug?: string;
  blog_cat?: any;
}

/**
 * All entries of the collection (ordered by createdAt DESC).
 */
export async function findMany(options?: {
  where?: Record<string, any>;
}): Promise<any[]> {
  const rows = await findManyDynamic(TABLE_NAME, options);
  return Array.isArray(rows) ? rows : [];
}

/**
 * Single entry by id (null when it does not exist).
 */
export async function findById(id: string): Promise<any | null> {
  const rows = (await findUniqueDynamic(TABLE_NAME, id)) as any[];
  return Array.isArray(rows) && rows.length > 0 ? rows[0] : null;
}

/**
 * Insert an entry into the dynamic table.
 */
export async function create(data: Record<string, any>): Promise<any> {
  return createDynamic(TABLE_NAME, data);
}

/**
 * Update an entry of the dynamic table.
 */
export async function update(
  id: string,
  data: Record<string, any>
): Promise<any> {
  return updateDynamic(TABLE_NAME, id, data);
}

/**
 * Delete an entry of the dynamic table.
 */
export async function remove(id: string): Promise<any> {
  return deleteDynamic(TABLE_NAME, id);
}

/**
 * CollectionType metadata (fields, relations, ...) for this collection.
 */
export async function getCollectionType(): Promise<any> {
  return prisma.collectionType.findUnique({
    where: { name: COLLECTION_NAME },
  });
}

/**
 * Field definitions of this collection (includes relation fields).
 */
export async function getFields(): Promise<Field[]> {
  const collectionType = await getCollectionType();
  const fields = (collectionType && (collectionType.fields as any)) || null;
  return fields && Array.isArray(fields.fields)
    ? (fields.fields as Field[])
    : [];
}
